### ISSUE TITLE
Running the CLI inside of a Github action triggers an stdin warning

### ISSUE THREAD

**Issue by janpieterz** [prettier/prettier-cli#14]
See the run [here](https://github.com/janpieterz/prettier-cli-repro/actions/runs/9688136493/job/26734102329?pr=1). 

> Run npx prettier --write .
> Error:  UndefinedParserError: No parser could be inferred for file "stdin".
> Error: Process completed with exit code 1.

Looks like something is falsy around this detection of TTY on GitHub runners (we've ran into other odd issues with that but I am struggling to find a quick fix).

**Comment by janpieterz** [comment]
Looks like [this pull request](https://github.com/janpieterz/prettier-cli-repro/pull/2/files) fixes it - based off of [this GitHub Actions thread](https://github.com/actions/runner/issues/241).

**Comment by mareksuscak** [comment]
I'm seeing this on my computer as of the last version update.

**Comment by fabiospampinato** [comment]
Does anyone have a repro that I can try locally? 🤔 "npx prettier --write ." doesn't do it for me.

**Comment by fabiospampinato** [comment]
[This commit](https://github.com/prettier/prettier-cli/commit/55382e95d7ea5755a71bd59fdd6f89684aea6211) should fix it in the next release.

**Comment by mareksuscak** [comment]
@fabiospampinato happy to help test this fix. Is there a pre-release available on npm yet?

**Comment by fabiospampinato** [comment]
@mareksuscak not yet, but I've asked the maintainers to make a new release, it shouldn't take too long.

**Comment by fabiospampinato** [comment]
@mareksuscak alpha10 just got released

**Comment by fabiospampinato** [comment]
@mareksuscak could you check if this fixes the issue for you? Thanks.
