### ISSUE TITLE
Force formatter for non-standard file extensions

### ISSUE THREAD

**Issue by kalaschnik** [prettier/prettier-cli#6]
Hey,

I am working on a JavaScript OSA (applescript) project. Those files typically have an `jxa` file extension. Unfortunately, I cannot get Prettier to auto-format those files on save. Since prettier identifies files based on extensions only?

![image](https://github.com/prettier/prettier-cli/assets/9831678/d344e08e-3f8c-4b1e-8970-1f139c1c8ab3)

Thus, I installed the prettier CLI. However, there is no flag to format a file and force syntax onto it. Right now, I am running, manually:

```bash
mv test.jxa test.js && prettier --write test.js && mv test.js test.jxa
```

Is there already a clever way to do this?

**Comment by fabiospampinato** [comment]
Basically if Prettier can't infer a parser for a given file it will ignore it, but you can specify a parser manually with the `--parser` flag, e.g. `--parser meriyah`.

If that file is part of a larger project that needs formatting I'd recommend setting that configuration once in [`.prettierrc`](https://prettier.io/docs/en/configuration#configuration-overrides) instead.

**Comment by kalaschnik** [comment]
Awesome! Thanks. Not sure why this is missing in the docs: https://prettier.io/docs/en/cli.html?
