### ISSUE TITLE
No matching version found for kasi@^1.1.0

### ISSUE THREAD

**Issue by dannacool** [prettier/prettier-cli#8]
node version: v14.21.3

**Comment by dannacool** [comment]
i am trying to install  prettier@next. emit error No matching version found for kasi@^1.1.0. It was specified as a dependency of '@prettier/cli'

**Comment by fabiospampinato** [comment]
What command are you executing exactly? Do you have some kind of proxy for the registry? I can't reproduce this issue right now.

**Comment by dannacool** [comment]
Thank you for your response. Perhaps it was my improper usage.

**Comment by dannacool** [comment]
> What command are you executing exactly? Do you have some kind of proxy for the registry? I can't reproduce this issue right now.


Thanks for your response. Perhaps it was my improper usage.
